[package]
name = "frontend-forge-extension-publisher"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flate2.workspace = true
frontend-forge-common = { path = "../common" }
k8s-openapi.workspace = true
kube.workspace = true
snafu.workspace = true
tar.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
