[package]
name = "frontend-forge-controller-bin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "frontend-forge-controller"
path = "src/main.rs"

[[bin]]
name = "frontend-extension-controller"
path = "src/frontend_extension_controller.rs"

[dependencies]
frontend-forge-controller = { path = "../controller" }
tokio.workspace = true
