{{- if and .Values.frontendForgeController.enabled .Values.frontendForgeController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "name" "frontend-forge-controller" "component" "runtime-controller") | nindent 4 }}
---
{{- end }}
{{- if .Values.frontendForgeRunner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.runnerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "name" "frontend-forge-runner" "component" "runtime-runner") | nindent 4 }}
---
{{- end }}
{{- if and .Values.frontendExtensionController.enabled .Values.frontendExtensionController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.extensionControllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "name" "frontend-extension-controller" "component" "extension-controller") | nindent 4 }}
---
{{- end }}
{{- if .Values.frontendForgeExtensionPackager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.extensionPackagerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "name" "frontend-forge-extension-packager" "component" "extension-packager") | nindent 4 }}
---
{{- end }}
{{- if .Values.frontendForgeExtensionPublisher.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.extensionPublisherServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "name" "frontend-forge-extension-publisher" "component" "extension-publisher") | nindent 4 }}
---
{{- end }}
{{- if and .Values.frontendForgeExtensionApi.enabled .Values.frontendForgeExtensionApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.extensionApiServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "name" "frontend-forge-extension-api" "component" "extension-api") | nindent 4 }}
{{- end }}
