{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "name" "frontend-forge-controller" "component" "webhook") | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: frontend-forge-controller
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  ports:
    - name: https-webhook
      port: {{ .Values.webhook.service.port }}
      targetPort: 9443
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.validatingWebhookName }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "name" "frontend-forge-controller" "component" "webhook") | nindent 4 }}
webhooks:
  - name: frontendintegrations.frontend-forge.kubesphere.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ .Values.webhook.service.name }}
        namespace: {{ .Release.Namespace }}
        path: /validate/frontendintegrations
        port: {{ .Values.webhook.service.port }}
      caBundle: ""
    rules:
      - apiGroups:
          - frontend-forge.kubesphere.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - frontendintegrations
        scope: Cluster
{{- end }}
