{{- $apiServiceAvailable := .Capabilities.APIVersions.Has "extensions.kubesphere.io/v1alpha1/APIService" -}}
{{- if and .Values.extensionApi.enabled .Values.extensionApi.apiService.enabled (or (not .Values.extensionApi.apiService.onlyIfApiResourceExists) $apiServiceAvailable) }}
apiVersion: extensions.kubesphere.io/v1alpha1
kind: APIService
metadata:
  name: {{ include "frontend-forge.extensionApiAPIServiceName" . | quote }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "component" "extension-api") | nindent 4 }}
spec:
  group: {{ include "frontend-forge.extensionApiAPIServiceGroup" . | quote }}
  version: {{ include "frontend-forge.extensionApiAPIServiceVersion" . | quote }}
  url: {{ include "frontend-forge.extensionApiAPIServiceURL" . | quote }}
  {{- with .Values.extensionApi.apiService.caBundle }}
  caBundle: {{ . | quote }}
  {{- end }}
  {{- if ne .Values.extensionApi.apiService.insecureSkipTLSVerify nil }}
  insecureSkipTLSVerify: {{ .Values.extensionApi.apiService.insecureSkipTLSVerify }}
  {{- end }}
status:
  state: Available
{{- end }}
