{{- if and .Values.controller.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.serviceAccountName" . }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "component" "runtime-controller") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
{{- end }}
{{- if and .Values.controller.enabled .Values.runner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.runnerServiceAccountName" . }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "component" "runtime-runner") | nindent 4 }}
  {{- with .Values.runner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.runner.serviceAccount.automount }}
---
{{- end }}
{{- if and .Values.migration.fiToFe.enabled .Values.migration.fiToFe.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.fiToFeMigratorServiceAccountName" . }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "component" "fi-to-fe-migrator") | nindent 4 }}
  {{- with .Values.migration.fiToFe.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.migration.fiToFe.serviceAccount.automount }}
---
{{- end }}
{{- if and .Values.extensionController.enabled .Values.extensionController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.extensionControllerServiceAccountName" . }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "component" "extension-controller") | nindent 4 }}
  {{- with .Values.extensionController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.extensionController.serviceAccount.automount }}
---
{{- end }}
{{- if and .Values.extensionController.enabled .Values.extensionPackager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.extensionPackagerServiceAccountName" . }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "component" "extension-packager") | nindent 4 }}
  {{- with .Values.extensionPackager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.extensionPackager.serviceAccount.automount }}
---
{{- end }}
{{- if and .Values.extensionController.enabled .Values.extensionPublisher.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.extensionPublisherServiceAccountName" . }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "component" "extension-publisher") | nindent 4 }}
  {{- with .Values.extensionPublisher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.extensionPublisher.serviceAccount.automount }}
---
{{- end }}
{{- if and .Values.extensionApi.enabled .Values.extensionApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend-forge.extensionApiServiceAccountName" . }}
  labels:
    {{- include "frontend-forge.componentLabels" (dict "root" . "component" "extension-api") | nindent 4 }}
  {{- with .Values.extensionApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.extensionApi.serviceAccount.automount }}
{{- end }}
